name: design_system
description: Dart package to manage Design System
version: 0.0.1+1
publish_to: none

environment:
  sdk: '>=3.8.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.21.2
  flutter_scale_tap: ^1.0.5
  extended_image: ^10.0.1
  gap: ^3.0.1
  flutter_gen: ^5.12.0
  theme_tailor: ^3.1.1
  theme_tailor_annotation: ^3.1.1
  pinput: ^5.0.2
  easy_localization: ^3.0.8

dev_dependencies:
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/colors/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/icons/1.5x/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
    - assets/icons/4.0x/
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/press_start_2p/PressStart2P-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: false
    lottie: false
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      style: dot-delimiter
      class_name: Assets
    exclude:
      [
        'assets/icons/1.5x/*',
        'assets/icons/2.0x/*',
        'assets/icons/3.0x/*',
        'assets/icons/4.0x/*'
      ]
