name: aezakmi_mini_app
description: App for painting
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.8.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  api:
    path: packages/api
  design_system:
    path: packages/design_system


  mobx: 2.5.0
  flutter_mobx: 2.3.0
  provider: 6.1.5
  auto_route: 10.2.0
  connectivity_plus: 7.0.0
  dio: 5.9.0
  easy_localization: 3.0.8
  get_it: 9.0.5
  injectable: 2.6.0
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  flutter_gen: 5.12.0
  gap: 3.0.1
  overlay_support: 2.1.0
  shared_preferences: ^2.5.3
  path_provider: 2.1.5
  firebase_core: 4.4.0
  firebase_auth: 6.1.4
  sentry_flutter: 9.8.0
  sentry_logging: 9.8.0
  image_picker: 1.0.7
  image_gallery_saver: 2.0.3
  firebase_ui_firestore: 2.0.1
  firebase_storage: 13.0.6
  shimmer: 3.0.0

  flutter_hooks: any
dev_dependencies:
  build_runner: 2.10.1
  freezed: 3.2.3
  auto_route_generator: 10.2.5
  injectable_generator: 2.9.1
  json_serializable: 6.11.1
  mobx_codegen: 2.7.4

  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
