name: api
description: Dart package to manage API calls
version: 0.0.2
publish_to: none

environment:
  sdk: '>=3.8.0-0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  retrofit: ^4.9.0
  rxdart: ^0.28.0
  socket_io_client: ^3.1.2

dev_dependencies:
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  retrofit_generator: ^10.1.4

flutter:
  generate: true
